SCALE Job started on Sun 2025-09-07 03:42:13 
With Host name BROHMANT 
working directory C:\Users\tbroh\AppData\Local\Temp\scale.tbroh.27068 
and process id 27068. 
Input file named C:\Users\tbroh\MCNP_INPUTS\python\scalePowerCreator\scaleRun\PebbleDecay1.inp 
and output file named C:\Users\tbroh\MCNP_INPUTS\python\scalePowerCreator\scaleRun\PebbleDecay1.out 
---------------------------------------------------------- 
  Now executing origen.exe                      
